export const GET_TOP_REPOSITORYES_REQUEST = "GET_TOP_REPOSITORYES_REQUEST";
export const GET_TOP_REPOSITORYES_SUCCESS = "GET_TOP_REPOSITORYES_SUCCESS";
export const GET_TOP_REPOSITORYES_ERROR = "GET_TOP_REPOSITORYES_ERROR";
